### ISSUE TITLE
请问速度如何呀

### ISSUE THREAD

**Issue by LRY89757** [DDGRCF/sparseinst_ncnn_demo#1]
请问速度如何呀，是否有与其他推理框架的对比分析

**Comment by DDGRCF** [comment]
> 请问速度如何呀，是否有与其他推理框架的对比分析
您好， 目前我只与onnxruntime进行对比，速度的话在最新的readme上有写

**Comment by LRY89757** [comment]
> > 请问速度如何呀，是否有与其他推理框架的对比分析
> > 您好， 目前我只与onnxruntime进行对比，速度的话在最新的readme上有写
好的好的，了解
